import Link from "next/link";
import { redirect } from "next/navigation";
import {
  refreshDemoExamplesAction,
  refreshOneDemoExampleAction,
} from "@/app/admin/analyzer/actions";
import { SetupNeeded } from "@/components/setup-needed";
import { getCurrentUser } from "@/lib/auth";
import { demoCompetitorPool } from "@/lib/demo-competitors";
import { DEMO_ANALYZER_VERSION, getDemoExamples } from "@/lib/demo-examples";
import type { DemoExampleResult } from "@/lib/database.types";
import { formatDateTime } from "@/lib/format";
import { isMasterAdminEmail } from "@/lib/master-admin";
import { getSupabaseAdminClient } from "@/lib/supabase/admin";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "Demo Examples | LaunchRadar",
};

type PoolStatus = {
  name: string;
  url: string;
  category: string;
  active: boolean;
  latest: DemoExampleResult | null;
};

async function recentDemoRows() {
  if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {
    return [];
  }

  const supabase = getSupabaseAdminClient();
  const { data } = await supabase
    .from("demo_example_results")
    .select("*")
    .order("updated_at", { ascending: false })
    .limit(100);

  return data ?? [];
}

function latestRowsByName(rows: DemoExampleResult[]) {
  const latest = new Map<string, DemoExampleResult>();

  for (const row of rows) {
    if (!latest.has(row.name)) {
      latest.set(row.name, row);
    }
  }

  return latest;
}

function JsonBlock({ value }: { value: unknown }) {
  return (
    <pre className="max-h-72 overflow-auto rounded-md bg-ink p-3 text-xs leading-5 text-white">
      {JSON.stringify(value, null, 2)}
    </pre>
  );
}

function statusClass(status?: string) {
  if (status === "success") {
    return "bg-moss/10 text-moss";
  }

  if (status === "partial") {
    return "bg-coral/10 text-coral";
  }

  return "bg-red-50 text-red-700";
}

function formatMaybeDate(value: string | null | undefined) {
  return value ? formatDateTime(value) : "Never";
}

export default async function DemoExamplesAdminPage() {
  const user = await getCurrentUser();

  if (!user) {
    redirect("/login");
  }

  if (!isMasterAdminEmail(user.email)) {
    redirect("/dashboard");
  }

  if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {
    return (
      <SetupNeeded
        title="Demo examples unavailable"
        message="SUPABASE_SERVICE_ROLE_KEY is required to inspect and refresh cached homepage examples."
      />
    );
  }

  const [cache, rows] = await Promise.all([getDemoExamples(), recentDemoRows()]);
  const latestByName = latestRowsByName(rows);
  const poolStatuses: PoolStatus[] = demoCompetitorPool.map((competitor) => ({
    ...competitor,
    latest: latestByName.get(competitor.name) ?? null,
  }));
  const failures = rows
    .filter((row) => row.status === "failed")
    .slice(0, 12);

  return (
    <main className="mx-auto flex min-h-[calc(100vh-72px)] w-full max-w-6xl flex-col gap-6 px-6 py-10">
      <section className="rounded-lg border border-ink/10 bg-white p-6 shadow-soft">
        <Link href="/dashboard/admin" className="text-sm font-semibold text-moss">
          Back to admin
        </Link>
        <div className="mt-3 flex flex-col justify-between gap-4 md:flex-row md:items-start">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-moss">
              Homepage proof
            </p>
            <h1 className="mt-2 text-3xl font-semibold text-ink">
              Demo examples
            </h1>
            <p className="mt-2 max-w-2xl text-sm leading-6 text-ink/60">
              Cached examples are generated by the deterministic analyzer and
              never refreshed during public homepage render.
            </p>
          </div>
          <form action={refreshDemoExamplesAction}>
            <button className="h-10 rounded-md bg-moss px-4 text-sm font-semibold text-white">
              Refresh examples
            </button>
          </form>
        </div>
      </section>

      <section className="grid gap-4 md:grid-cols-4">
        {[
          ["Visible examples", cache.examples.length],
          ["Pool size", demoCompetitorPool.filter((item) => item.active).length],
          ["Recent failures", failures.length],
          ["Analyzer", DEMO_ANALYZER_VERSION],
        ].map(([label, value]) => (
          <article key={label} className="rounded-lg border border-ink/10 bg-white p-4">
            <p className="text-xs font-semibold uppercase tracking-[0.16em] text-ink/45">
              {label}
            </p>
            <p className="mt-3 text-lg font-semibold text-ink">{value}</p>
          </article>
        ))}
      </section>

      <section className="rounded-lg border border-ink/10 bg-white p-5">
        <div className="flex flex-col justify-between gap-3 md:flex-row md:items-center">
          <div>
            <h2 className="text-lg font-semibold text-ink">Current homepage set</h2>
            <p className="mt-1 text-sm text-ink/55">
              Last refresh: {formatMaybeDate(cache.updated_at)} - Next:{" "}
              {formatMaybeDate(cache.next_refresh_at)}
            </p>
          </div>
          <span className={`rounded-full px-3 py-1 text-xs font-semibold ${statusClass(cache.refresh_status === "ready" ? "success" : "partial")}`}>
            {cache.refresh_status}
          </span>
        </div>

        {cache.examples.length ? (
          <div className="mt-5 grid gap-4 md:grid-cols-3">
            {cache.examples.map((example) => (
              <article key={`${example.name}:${example.source_url}`} className="rounded-md border border-ink/10 p-4 text-sm">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <p className="font-semibold text-ink">{example.name}</p>
                    <p className="mt-1 text-xs text-ink/50">{example.category}</p>
                  </div>
                  <span className="rounded-full bg-paper px-2 py-1 text-xs font-semibold text-ink/55">
                    {example.confidence}
                  </span>
                </div>
                <p className="mt-3 line-clamp-2 leading-6 text-ink/65">
                  {example.positioning}
                </p>
                <dl className="mt-3 space-y-1 text-xs text-ink/60">
                  <div>
                    <dt className="inline font-semibold text-ink">Pricing: </dt>
                    <dd className="inline">{example.pricing}</dd>
                  </div>
                  <div>
                    <dt className="inline font-semibold text-ink">CTA: </dt>
                    <dd className="inline">{example.cta}</dd>
                  </div>
                  <div>
                    <dt className="inline font-semibold text-ink">Verified: </dt>
                    <dd className="inline">{formatMaybeDate(example.last_verified_at)}</dd>
                  </div>
                </dl>
                <details className="mt-3 rounded-md bg-paper p-3 text-xs leading-5 text-ink/65">
                  <summary className="cursor-pointer font-semibold text-ink">
                    Evidence
                  </summary>
                  <p className="mt-2">{example.evidence_text}</p>
                  <a
                    href={example.source_url}
                    target="_blank"
                    rel="noreferrer"
                    className="mt-2 inline-flex font-semibold text-moss"
                  >
                    Source
                  </a>
                </details>
              </article>
            ))}
          </div>
        ) : (
          <p className="mt-4 rounded-md bg-paper p-4 text-sm text-ink/65">
            No verified examples are currently available. Use manual refresh to
            populate the cache; the public homepage will not run live scans.
          </p>
        )}
      </section>

      <section className="rounded-lg border border-ink/10 bg-white p-5">
        <h2 className="text-lg font-semibold text-ink">Curated pool</h2>
        <div className="mt-4 overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="text-ink/50">
              <tr>
                <th className="py-2">Product</th>
                <th>Category</th>
                <th>Status</th>
                <th>Last success</th>
                <th>Last failure</th>
                <th>Failure reason</th>
              </tr>
            </thead>
            <tbody>
              {poolStatuses.map((item) => (
                <tr key={item.name} className="border-t border-ink/10 align-top">
                  <td className="py-3">
                    <a href={item.url} target="_blank" rel="noreferrer" className="font-semibold text-ink hover:text-moss">
                      {item.name}
                    </a>
                  </td>
                  <td>{item.category}</td>
                  <td>
                    <span className={`rounded-full px-2 py-1 font-semibold ${statusClass(item.latest?.status)}`}>
                      {item.latest?.status ?? (item.active ? "pending" : "inactive")}
                    </span>
                  </td>
                  <td>
                    {item.latest?.status === "success"
                      ? formatMaybeDate(item.latest.last_verified_at)
                      : "Never"}
                  </td>
                  <td>
                    {item.latest?.status === "failed"
                      ? formatMaybeDate(item.latest.updated_at)
                      : "None"}
                  </td>
                  <td className="max-w-xs text-ink/60">
                    <div className="flex flex-col gap-2">
                      <span>{item.latest?.failure_reason ?? ""}</span>
                      <form action={refreshOneDemoExampleAction}>
                        <input type="hidden" name="name" value={item.name} />
                        <button className="rounded-md border border-ink/10 bg-white px-2 py-1 text-xs font-semibold text-ink/60 hover:text-moss">
                          Refresh one
                        </button>
                      </form>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="grid gap-4 lg:grid-cols-2">
        <article className="rounded-lg border border-ink/10 bg-white p-5">
          <h2 className="text-lg font-semibold text-ink">Recent failures</h2>
          {failures.length ? (
            <div className="mt-4 space-y-3">
              {failures.map((row) => (
                <div key={row.id} className="rounded-md bg-paper p-3 text-xs leading-5 text-ink/65">
                  <p className="font-semibold text-ink">{row.name}</p>
                  <p>{row.failure_reason ?? "Unknown failure"}</p>
                  <p className="mt-1 text-ink/45">{formatMaybeDate(row.updated_at)}</p>
                </div>
              ))}
            </div>
          ) : (
            <p className="mt-4 rounded-md bg-paper p-4 text-sm text-ink/65">
              No recent refresh failures.
            </p>
          )}
        </article>
        <article className="rounded-lg border border-ink/10 bg-white p-5">
          <h2 className="text-lg font-semibold text-ink">Latest analyzer output</h2>
          <div className="mt-4">
            <JsonBlock value={rows[0] ?? null} />
          </div>
        </article>
      </section>
    </main>
  );
}
